# Generated by Django 4.2 on 2024-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('proid', models.AutoField(primary_key=True, serialize=False)),
                ('prodname', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'lokiapp_product',
            },
        ),
    ]
